### ISSUE TITLE
New version of Iron Coal Mod version issues

### ISSUE THREAD

**Issue by BedrockLegends** [Flamebom/IronCoals#3]
![2020-08-18_23 49 09](https://user-images.githubusercontent.com/48525410/90593414-7662ce00-e1ad-11ea-9406-d380e9c58d5e.png)

Your mods tells everyone that it works on 1.16.2, but it does not and refuses to load, can you make sure you label it the right version instead of saying it works for 1.16.2 when it does not

**Comment by Flamebom** [comment]
Oops, I forgot to add a version range, will probably fix that in next version

**Comment by Flamebom** [comment]
I fixed the version number, so it should work now in the newest version
gonna keep the issue open though cause i don't actaully have a 1.16.2 forge version for proof

**Comment by Flamebom** [comment]
gonna mark it as closed and reopen it if you still have the same issue
