### ISSUE TITLE
Fabric port

### ISSUE THREAD

**Issue by Minenash** [Flamebom/IronCoals#6]
Someone in the fabric discord requested a fabric port of the mod, and I noticed that there were some requests on your curseforge page. After checking the license, I made a fabric port of it at [https://github.com/Minenash/Iron-Coal-Fabric-Unoffical](https://github.com/Minenash/Iron-Coal-Fabric-Unoffical). The current differences are that it doesn't have a config nor the iron torch.

If you want to release it as a fabric version on your page, then I can add the config and the iron torch. If you don't (and if you're okay if I post the port) than I'll add a torch for every level (and also add aeon coal block), but probably not add the config

Post-edit: Another small difference is that I changed the tooltip to show how many items it can smelt since I find that more useful

**Comment by Flamebom** [comment]
Hey, 
If your cool with it, I can add you to the curseforge mod page, and you can upload your fabric ports (as long as they don't break TOS of course :) . The content of both mods don't need to be exactly the same either, so if you want to add anything that is isn't in forge I'm ok with it too.

**Comment by Minenash** [comment]
That sounds good, though if we do have slightly different features, we should have that somewhere on that page

**Comment by Flamebom** [comment]
I've added an area called "fabric only features" that you can add the extra features your port has. As time goes on I'll try to implement those features in forge.

**Comment by Minenash** [comment]
Sounds good. Btw, what was your process to make the textures, so I can apply them too the new items?

**Comment by Flamebom** [comment]
I use an art editor, take the shape of the base item then use a color palette based off of vanilla items. For instance, I use the iron ingot from Minecraft to make my iron coal. Then I reshade the sprite until it looks more normal.

**Comment by Minenash** [comment]
Which block/item was used for the color palette of the aeon coal?

**Comment by Flamebom** [comment]
Nothing, it was requested by someone else and there's nothing to base it off of. Though if I remade it I'd probably use netherstar as reference.

**Comment by Minenash** [comment]
Pushed the release. It has the new torches, but doesn't have the aeon coal block, because I was having troubles getting that to look good
